### ISSUE TITLE
Detaching cluster nodes from the utility network?

### ISSUE THREAD

**Issue by tatupesonen** [UpCloudLtd/uks-instructions#34]
Hi! Is it possible to detach the cluster nodes from the utility network using Terraform? We'll have multiple clusters in the future and they're not allowed to intercommunicate on the network level due to regulatory compliance.

**Comment by thevilledev** [comment]
Hey, thanks for reaching out!

We are working on supporting a parameter through which you can control whether utility network interfaces are enabled on the nodes or not. This is can be defined upon cluster creation.

Generating the Terraform configuration with our [Terraform Exporter](https://hub.upcloud.com/terraform) & importing individual resources work after some manual modifications to the configs. This is a bit tedious at the moment and has to be done in a specific way so that the external IP of the node doesn't change. For a bit better UX, I would recommend doing the following workaround over the UI:

- Shut down a worker node
- Remove utility network interface under "Network" tab
- Start worker node

I'll keep this issue open until we have rolled out the new parameter.

**Comment by thevilledev** [comment]
Hey @tatupesonen, happy to let you know that you can now control this per node group with the [`utility_network_access` flag](https://registry.terraform.io/providers/UpCloudLtd/upcloud/latest/docs/resources/kubernetes_node_group#utility_network_access)!

**Comment by tatupesonen** [comment]
Awesome, thanks! @thevilledev
